### PR TITLE
Adding some missing comments

### PR DESCRIPTION
**Pull request by nimrof**
Only 493 missing comments left :)

a few places i have change function from public -> private

### CODE REVIEW

**Comment by trojanobelix** [comment]
Looks good. Merge!

**Comment by CANopenNode** [comment]
> Only 493 missing comments left :)

One more reason, why to remove obsolete large files like CanOpenXDD.cs, CanOpenXML.cs, Bridge.cs

@trojanobelix, what do you think about it? (see https://github.com/CANopenNode/CANopenEditor/pull/77#issuecomment-2024952840)

**Comment by trojanobelix** [comment]
Agree for Bridge and CanOpenXML, not sure about CanOpenXDD. But we will see which stuff is needed.

**Comment by CANopenNode** [comment]
> Agree for Bridge and CanOpenXML, not sure about CanOpenXDD. But we will see which stuff is needed.

There if CanOpenXDD_1_1, which is fully operational. 
CanOpenXDD is older implementation of an older version of the same standard and is not working well.

**Comment by trojanobelix** [comment]
I know, but unfortunately some test programmes only support the old version. I know that I therefore needed the XML V1.0 export more often than I would have liked, and I was very glad that CANopenEditor supports the export.

But I don't want to argue against it in principle.

Or perhaps one of you knows another good converter for CANopen files. It's really not the main task of the software.

But being able to import as many formats as possible would, in my opinion, be in the target focus. Nothing is more annoying than having all the necessary information in an (albeit old) configuration format but not being able to import it.



Dirk Wieschebrock
Projektmanager
Project Manager


technotrans SE
Robert-Linnemann-Straße 17Firmensitz: Sassenberg
48336Sassenberg
Amtsgericht Münster HRB 17351
P:+49 2583 301 1217 | F:+49 2583 301 1030
Vors. des Aufsichtsrats: Peter Baumgartner
***@***.*** | www.technotrans.de
Vorstand: Michael Finger (CEO), Robin Schaede
Von: Janez ***@***.***>
Gesendet: Donnerstag, 4. April 2024 15:20
An: CANopenNode/CANopenEditor ***@***.***>
Cc: Wieschebrock, Dirk ***@***.***>; Mention ***@***.***>
Betreff: [EXTERNAL] Re: [CANopenNode/CANopenEditor] Adding some missing comments (PR #96)


Agree for Bridge and CanOpenXML, not sure about CanOpenXDD. But we will see which stuff is needed.

There if CanOpenXDD_1_1, which is fully operational.
CanOpenXDD is older implementation of an older version of the same standard and is not working well.

-

**Comment by nimrof** [comment]
I do not have a need to remove support a format if it still in use, especially if it is in use by someone that is a active contributor to the project.

**Comment by CANopenNode** [comment]
> I know, but unfortunately some test programmes only support the old version.

I didn't know for that. Than it should stay, I think.

**Pull request merged**
