### PR TITLE
add dependabot to keep github action up-to-date

### PR DESCRIPTION
**Pull request by nimrof**
This sets up dependabot to check if the actions (like actions/upload-artifact) is up to date,
if it is not it will automatically make pr. once a week.

afik there are now three actions that needs updating so it should make three pr.
image

It can also be used to keep nugets up-to-date with a little more setup

### CODE REVIEW

**Review by trojanobelix — APPROVED** [review]
I have no idea about it, but it looks good :-)

**Comment by nimrof** [comment]
> I have no idea about it, but it looks good :-)

You will find out very soon 🤞

**Comment by nimrof** [comment]
or not.
@CANopenNode could you enable dependabot?

image

**Comment by CANopenNode** [comment]
Dependency graph and Dependabot alerts are now enabled. Something else necessary?

**Comment by nimrof** [comment]
Works now :), just look at all the pr. 
Not sure if it was just a delay or what

**Pull request merged**
