### PR TITLE
Allow instantly saving changes upon object change

### PR DESCRIPTION
**Pull request by uniederer**
When editing larger profiles, annoyingly you always have to click "save" prior changing the (sub-)object. While the software detects changes and asks the user whether to lose the changes or not, it does not provide any possibility to simply say "yes, i want to keep the changes, but now let me switch the object".

This patch changes adds this missing third option to the dialog. It also adds a checkbox allowing to suppress the dialog and automatically save changes upon object change to speed up editing.

_Remark_: I have no idea, why so many lines show up changed in this merge, looking at the diffs on my cloned repository, there are only a few lines that are actually changed, even with white-space comparison.

### CODE REVIEW

**Comment by trojanobelix** [comment]
Thanks for contributing. I have merged it in the feature branch._
The text "save changes" checkbox might be renamed to "Always save" and/or get a Tooltip . Save button can be smaller if more space needed for text. Just my 2ct.

**Comment by uniederer** [comment]
Ah, I should have PRed to the feature branch. Sorry, I have to admit, I didn't do much research on which branch to target prior creating the PR and just sticked to my main behaviour. Mea culpa.

As for the checkbox: Sure, feel free to rename it as you like. I just thought it might be worth adding. I also was considering to move that behaviour setting to the settings, but I was a bit short in time today, so I picked the more straight forward and obvious approach. In a perfect world we would probably bring up a custom dialog once and add a "remember my decision"-checkbox to it... what do you think?

**Comment by trojanobelix** [comment]
With the branch, I always decide spontaneously whether it should be in the feature or the bugfix branch. I have only recently created the two branches. I am also new here as a contributor. Therefore: No problem at all!

Yes, I also thought about whether it would be better in the settings dialogue. But that is too "far away" for me. I would also prefer the "Remember my decision" dialogue when saving for the first time. 
If you have time and feel like it: Feel free to implement it that way!

**Comment by trojanobelix** [comment]
I noticed that after changing an object and selecting another object from the list, the selected object is selected. Although you have pressed "Cancel".

So just not: "Cancel = Go back and stay on the object".

Can you reproduce and sent a bugfix PR in the bugfix release?

**Pull request closed without merging**
