### PR TITLE
include cli sw in release

### PR DESCRIPTION
**Pull request by nimrof**
The cli tool will now be included in releases and pr. artifact

### CODE REVIEW

**Review by trojanobelix — COMMENTED** [review]
Looks good! Thank you

**Review by CANopenNode — APPROVED** [review]

**Comment by DO4AF** [comment]
Thanks for merging this into main. Can't wait for the new release.
I am going to integrate the generation of OD in the build pipeline. This CLI enables that. Many thanks!

**Comment by CANopenNode** [comment]
@DO4AF, you can binaries for any PR under "Actions". The same as release. See the bottom of the page:
https://github.com/CANopenNode/CANopenEditor/actions/runs/11754468893

**Comment by DO4AF** [comment]
@CANopenNode thanks for this hint. I was using the binary for testing purposes and it works fine.

Since now the new release was available i included the new CANopenEditor in my project. As i am pulling a specific release, i was waiting for it to be available.

This is a part of my tool install script
```
mkdir -p .tools

if [ ! -d ".tools/CANopenEditor" ]; then
    echo "Downloading CANopenEditor ${CANOPENEDITOR_VERSION}"
    wget https://github.com/CANopenNode/CANopenEditor/releases/download/v${CANOPENEDITOR_VERSION}/CANopenEditor-v${CANOPENEDITOR_VERSION}-binary.zip
    unzip -q CANopenEditor-v${CANOPENEDITOR_VERSION}-binary.zip -d .tools/CANopenEditor
    rm CANopenEditor-v${CANOPENEDITOR_VERSION}-binary.zip
else
    echo "CANopenEditor ${CANOPENEDITOR_VERSION} already downloaded"
fi
```

and then i run the generation on the fly in the build somehow like this:
```
# Setup CANOpenNode settings
set(CANOPENNODE_BIN_DIR ${CMAKE_CURRENT_SOURCE_DIR}/.tools/CANopenEditor/net481 CACHE PATH "Path to CANopenEditor tool directory")
set(CANOPENNODE_GENERATOR "EDSSharp.exe")
set(CANOPENNODE_GEN_DIR ${CMAKE_CURRENT_SOURCE_DIR}/CANopenNode_STM32)
set(CANOPENNODE_XDD_FILE ${CMAKE_CURRENT_SOURCE_DIR}/CANopenNode_STM32/project.xdd)
set(CANOPENNODE_OD_C ${CANOPENNODE_GEN_DIR}/OD.c)
set(CANOPENNODE_OD_H ${CANOPENNODE_GEN_DIR}/OD.h)
set(CANOPENNODE_EXPORTER_TYPE "CanOpenNodeV4")

# Define the custom command for code generation
add_custom_command(
    OUTPUT ${CANOPENNODE_OD_C} ${CANOPENNODE_OD_H}
    COMMAND mono ${CANOPENNODE_BIN_DIR}/${CANOPENNODE_GENERATOR} --infile ${CANOPENNODE_XDD_FILE} --outfile ${CANOPENNODE_OD_C} --type ${CANOPENNODE_EXPORTER_TYPE}
    DEPENDS ${CANOPENNODE_GEN_DIR}/project.xdd ${CANOPENNODE_BIN_DIR}/${CANOPENNODE_GENERATOR}
    COMMENT "Generating Object Directory from ${CANOPENNODE_XDD_FILE}"
    VERBATIM
)

# Create a target for the code generation step
add_custom_target(
    generate_od ALL
    DEPENDS ${CANOPENNODE_OD_C} ${CANOPENNODE_OD_H}
)
```

Many thanks!

**Pull request merged**
